// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEF414EAMLTh8noOGtOKqxu2T-9_0NjU',
    appId: '1:935657167245:web:242cf149d6286ba514c5c4',
    messagingSenderId: '935657167245',
    projectId: 'quiz-app-flutter-flow',
    authDomain: 'quiz-app-flutter-flow.firebaseapp.com',
    storageBucket: 'quiz-app-flutter-flow.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIk3AjuWHRcpcNl4FbL0mOPI4wSHDbqAw',
    appId: '1:935657167245:android:5f6ab4b57a04d05214c5c4',
    messagingSenderId: '935657167245',
    projectId: 'quiz-app-flutter-flow',
    storageBucket: 'quiz-app-flutter-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05W_LiEejMkF2TlhP21PN3mR5Hu4lB7I',
    appId: '1:935657167245:ios:737669e70d6e216114c5c4',
    messagingSenderId: '935657167245',
    projectId: 'quiz-app-flutter-flow',
    storageBucket: 'quiz-app-flutter-flow.appspot.com',
    iosClientId: '935657167245-8libjpqtr1ga3hpcf4d5mseh1gib96qt.apps.googleusercontent.com',
    iosBundleId: 'com.extrawest.quizappff',
  );
}
